
name: Build & Publish SSC Report
on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ssc_pipeline/requirements.txt
      - name: Build HTML report
        run: |
          python ssc_pipeline/build_report.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ssc_pipeline/Auto_Report.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
