name: Build & Publish SSC Report

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 6 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ssc_pipeline/requirements.txt
          pip install matplotlib pandas

      - name: DIAG 1 - Mostrar primeros 60 lines de build_report.py y buscar 'nbconvert'
        run: |
          echo "== head build_report.py =="
          sed -n '1,60p' ssc_pipeline/build_report.py || true
          echo "== grep nbconvert =="
          grep -n "nbconvert" -n ssc_pipeline/build_report.py || echo "(no nbconvert)"

      - name: Build report (generates Auto_Report.html)
        env:
          SSC_ROOT: ${{ github.workspace }}
          SSC_CACHE_DIR: ${{ github.workspace }}/.ssc_cache
        run: |
          python ssc_pipeline/build_report.py
          mkdir -p public
          cp ssc_pipeline/Auto_Report.html public/index.html
          echo "== HEAD of generated HTML =="
          sed -n '1,20p' public/index.html || true

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

