
name: Update SSC Data
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ssc_pipeline/requirements.txt
      - name: Run updater
        env:
          SSC_ROOT: ${{ github.workspace }}
        run: python -m ssc_pipeline.ssc_pipeline.update_data
      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add main.csv
          git commit -m "Auto-update data $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
